---
- name: "{{ epics_modules[item].name }} | Fix configure/RELEASE to include RELEASE.local"
  ansible.builtin.lineinfile:
    path: "{{ epics_install_path }}/{{ item }}-{{ epics_modules[item].version }}/configure/RELEASE"
    search_string: '-include $(TOP)/RELEASE.local'
    line: '-include $(TOP)/../RELEASE.local'
  become: true

- name: "{{ epics_modules[item].name }} | Setup common plugins"
  ansible.builtin.copy:
    src: "{{ epics_install_path }}/{{ item }}-{{ epics_modules[item].version }}/iocBoot/EXAMPLE_commonPlugins.cmd"
    dest: "{{ epics_install_path }}/{{ item }}-{{ epics_modules[item].version }}/iocBoot/commonPlugins.cmd"
  become: true

- name: "{{ epics_modules[item].name }} | Setup common plugins request file"
  ansible.builtin.copy:
    src: "{{ epics_install_path }}/{{ item }}-{{ epics_modules[item].version }}/iocBoot/EXAMPLE_commonPlugin_settings.req"
    dest: "{{ epics_install_path }}/{{ item }}-{{ epics_modules[item].version }}/iocBoot/commonPlugin_settings.req"
  become: true
  
- name: "{{ epics_modules[item].name }} | Add configuration to configure/CONFIG_SITE"
  ansible.builtin.blockinfile:
    path: "{{ epics_install_path }}/{{ item }}-{{ epics_modules[item].version }}/configure/CONFIG_SITE"
    insertbefore: "BOF"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      WITH_ZLIB = YES
      WITH_TIFF = YES
      WITH_JPEG = YES
      WITH_PVA = YES
      XML2_INCLUDE += /usr/include/libxml2
  become: true
  
